### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by steverob** [ConferenceCloud/ruby-scaleengine#1]
Hi is there an updated version of this gem?

**Comment by jsimnz** [comment]
Its somewhat updated on an on going bases. Was there something specific your wondering about?

**Comment by jsimnz** [comment]
If there isn't a specific request you had in mind or fix that's needed I'll go ahead a close this issue in a few days.

Thanks.

**Comment by steverob** [comment]
Hey I'm sorry. It was a general question :) go ahead and close please.

## 

Regards
Steve Robinson
